services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"

  streamlit_app:
    build:
      context: .
    ports:
      - "8501:8501"
    depends_on:
      - qdrant
      - ollama
    volumes:
      - ./:/app  # Map the entire current directory to /app in the container
    environment:
      - PYTHONUNBUFFERED=1
