services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_models:/root/.ollama/models  # Persist Ollama models

  streamlit_app:
    build:
      context: .
    ports:
      - "8501:8501"
    depends_on:
      - qdrant
      - ollama
    volumes:
      - ./:/app  # Live code updates
      - ./ollama_models:/app/ollama_models  # Share models directory with Streamlit
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  qdrant_storage:
